service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-1

plugins:
  - serverless-webpack
  - serverless-openapi-documentation

functions:
  getProductsList:
    handler: src/handlers/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
          documentation: ${file(./serverless.doc.yml):documentation.endpoints.getProductsList}
  getProductsById:
    handler: src/handlers/getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
          documentation: ${file(./serverless.doc.yml):documentation.endpoints.getProductsById}

custom:
  documentation: ${file(./serverless.doc.yml):documentation}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
