# serverless-compose.yml
services:

  authorization-service:
    path: "authorization-service"

  product-service:
    path: "product-service"

  import-service:
    path: "import-service"
    params:
      sqsURL: ${product-service.sqsURL}
      sqsArn: ${product-service.sqsArn}
